---
title: "MyTime Dashboard"
output: 
  flexdashboard::flex_dashboard:
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
rm(list=ls())
library(ggplot2)
library(shiny)
library(flexdashboard)
library(plotly)
library(knitr)
library(dplyr)
library(reshape2)
library(viridis)
library(fmsb)
```

```{r global, include=FALSE, warning=FALSE}
setwd("C:/Users/Uzytkownik/Documents/Studia/prezentacja i wizualizacja/projekt/EPL_players")
data1 <- read.csv("pl_19-20.csv", encoding = "UTF-8", stringsAsFactors = FALSE,
                  strip.white=TRUE)
data1$Name <- substr(data1$Name, 1, length(data1$Name)-1)
data <- data1%>%filter(Appearances>=10)
data[data$Position=='Goalkeeper', 'Position'] <- 'Bramkarz'
data[data$Position=='Defender', 'Position'] <- 'Obrońca'
data[data$Position=='Midfielder', 'Position'] <- 'Pomocnik'
data[data$Position=='Forward', 'Position'] <- 'Napastnik'
data$Passes <- as.numeric(sub(",", "", data$Passes, fixed = TRUE))
data <- data %>% select(Name, Position, Appearances, Goals.conceded, Goals, Shots, Clean.sheets, Saves, Errors.leading.to.goal, Passes, Accurate.long.balls, High.Claims, Tackles, Blocked.shots, Duels.won, Duels.lost, Big.chances.created, Assists, Crosses, Interceptions, Clearances, Aerial.battles.won, Aerial.battles.lost, Headed.goals)


normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}


radar <- function(data, var1, var2, var3, var4, var5, var6, name1, name2, name3){
data[var1] <- normalize(data[var1])
data[var2] <- normalize(data[var2])
data[var3] <- normalize(data[var3])
data[var4] <- normalize(data[var4])
data[var5] <- normalize(data[var5])
data[var6] <- normalize(data[var6])

data2 <- data%>%
  filter(Name%in%c(name1, name2, name3)) %>%
  select((!!as.symbol(var1)), (!!as.symbol(var2)), (!!as.symbol(var3)), (!!as.symbol(var4)), 
         (!!as.symbol(var5)), (!!as.symbol(var6)), Name)
rownames(data2) <- data2$Name 
data2 <- data2[, -7]
data2 <- rbind(rep(1, 6), rep(0,6), data2)

scale_colours=c(viridis(3)[3], viridis(3)[2], magma(3)[2])
radarchart(data2, pcol=scale_colours, plwd=3, vlcex=0.7)
legend(x=1, 
       y=1.35, 
       legend = rownames(data2[-c(1,2),]), 
       bty = "n", pch=20 , col = scale_colours, cex = 0.7)
}
```


Selections {.sidebar}
===============================

Select the variables to display

```{r}

selectInput("name1",
                   label = "Choose a survey to display",
                   choices = unique(data$Name),
                   multiple = TRUE)
selectInput("name2",
                   label = "Choose a team to display",
                   choices = unique(data$Name),
                   multiple = TRUE)
selectInput("name3",
                 label = "Choose a WFM to display",
                 choices = unique(data$Name),
               multiple = TRUE)
selectInput("var1",
               label = "Choose a month to display",
               choices = names(data),
               multiple = TRUE)
selectInput("var2",
               label = "Choose a task to display",
               choices = names(data),
               multiple = TRUE)
selectInput("var3",
               label = "Level to display (SharedWork)",
               choices = names(data),
               multiple = TRUE)
selectInput("var4",
               label = "Level to display (SharedWork)",
               choices = names(data),
               multiple = TRUE)
selectInput("var5",
               label = "Level to display (SharedWork)",
               choices = names(data),
               multiple = TRUE)
selectInput("var6",
               label = "Level to display (SharedWork)",
               choices = names(data),
               multiple = TRUE)
# observe({
#    team <- input$team
#    wfm <- input$wfm
#    survey <- input$survey
#    if(length(team)>0 & length(wfm)>0 & length(survey)>0){
#    }
#    else if(length(team)>0 & length(wfm)>0 & length(survey)==0){
#    cho1 <- Quests_month %>% filter(Survey.Team %in% team & Survey.WFM %in% wfm) %>% pull(Survey.Abb)
#    updateSelectInput(session, "survey",
#          choices = cho1
#        )
#    }
#    else if(length(team)>0 & length(wfm)==0 & length(survey)==0){
#     cho1 <- Quests_month %>% filter(Survey.Team %in% team) %>% pull(Survey.Abb)
#     cho2 <- Quests_month %>% filter(Survey.Team %in% team) %>% pull(Survey.WFM)
#     updateSelectInput(session, "survey",
#          choices = cho1
#        )
#     updateSelectInput(session, "wfm",
#          choices = cho2
#        )
#    }
#    else if(length(team)==0 & length(wfm)==0 & length(survey)>0){
#     cho1 <- Quests_month %>% filter(Survey.Abb %in% survey) %>% pull(Survey.WFM)
#     cho2 <- Quests_month %>% filter(Survey.Abb %in% survey) %>% pull(Survey.Team)
#     updateSelectInput(session, "wfm",
#          choices = cho1
#        )
#     updateSelectInput(session, "team",
#          choices = cho2
#        )
#    }
#    else if(length(team)==0 & length(wfm)>0 & length(survey)==0){
#     cho1 <- Quests_month %>% filter(Survey.WFM %in% wfm) %>% pull(Survey.Team)
#     cho2 <- Quests_month %>% filter(Survey.WFM %in% wfm) %>% pull(Survey.Abb)
#     updateSelectInput(session, "team",
#          choices = cho1
#        )
#     updateSelectInput(session, "survey",
#          choices = cho2
#        )
#    }
#    else if(is.null(team) & is.null(wfm) & is.null(survey)){
#    updateSelectInput(session, "survey",
#          choices = Quests_month %>% pull(Survey.Abb) %>% unique()
#        )
#    updateSelectInput(session, "wfm",
#          choices = Quests_month %>% pull(Survey.WFM) %>% unique()
#        )
#    updateSelectInput(session, "team",
#          choices = Quests_month %>% pull(Survey.Team) %>% unique()
#        )
#    }
#    })

```

Surveys - plots
===================================== 

Column 
-------------------------------------

```{r}
suppressWarnings(renderPlot({
     radar(data, input$var1, input$var2, input$var3, input$var4, input$var5, input$var6, input$name1, input$name2, input$name3)
   }))
```

<!-- ### Top 30 surveys -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_survey(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->

<!-- ``` -->

<!-- ### YoY -->


<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_yoy(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->

<!-- Column {data-width=300} -->
<!-- ------------------------------------- -->

<!-- ### Monthly -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_month(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->


<!-- ### Processing -->
<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_tasks(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->

<!-- Surveys - tables -->
<!-- ===================================== -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Hours by Survey -->

<!-- ```{r} -->
<!-- renderTable(table_quest(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Hours by Month -->

<!-- ```{r} -->
<!-- renderTable(table_month(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->

<!-- ### Hours by Task -->

<!-- ```{r} -->
<!-- renderTable(table_task(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->


<!-- Shared Work - Teams -->
<!-- ===================================== -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Shared Work Team -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_team(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->

<!-- ### Shared Work Energy/SIRS/Healthcare -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_energy(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Shared Work General Industry -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_gi(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->


<!-- ### Shared Work Professionals -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_prof(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->


<!-- Shared Work - Full -->
<!-- ===================================== -->


<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_full(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->

<!-- Stats per Team {data-orientation=rows} -->
<!-- ===================================== -->

<!-- Row {data-height=350} -->
<!-- ------------------------------------- -->

<!-- ### Table stats per Team -->

<!-- ```{r} -->
<!-- renderTable(table_stats(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->

<!-- Row {data-height=650} -->
<!-- ------------------------------------- -->

<!-- ### Plot stats overall -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_team_stats(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->
