---
title: "Analiza statystyk piłkarzy Premier League"
output: 
  flexdashboard::flex_dashboard:
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
rm(list=ls())
library(ggplot2)
library(shiny)
library(flexdashboard)
library(plotly)
library(knitr)
library(dplyr)
library(reshape2)
library(viridis)
library(fmsb)
```

```{r global, include=FALSE, warning=FALSE}
# setwd("C:/Users/Uzytkownik/Documents/Studia/prezentacja i wizualizacja/projekt/EPL_players")
setwd("C:/Users/filip-mordarski/priv/EPL_players")
data1 <- read.csv("pl_19-20.csv", encoding = "UTF-8", stringsAsFactors = FALSE,
                  strip.white=TRUE)
data1$Name <- substr(data1$Name, 1, length(data1$Name)-1)
data <- data1%>%filter(Appearances>=10)
data[data$Position=='Goalkeeper', 'Position'] <- 'Bramkarz'
data[data$Position=='Defender', 'Position'] <- 'Obrońca'
data[data$Position=='Midfielder', 'Position'] <- 'Pomocnik'
data[data$Position=='Forward', 'Position'] <- 'Napastnik'
data$Passes <- as.numeric(sub(",", "", data$Passes, fixed = TRUE))
data <- data %>% select(Name, Position, Appearances, Goals.conceded, Goals, Shots, Clean.sheets, Saves, Errors.leading.to.goal, Passes, Accurate.long.balls, High.Claims, Tackles, Blocked.shots, Duels.won, Duels.lost, Big.chances.created, Assists, Crosses, Interceptions, Clearances, Aerial.battles.won, Aerial.battles.lost, Headed.goals)


normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}


radar <- function(data, var, names){

temp <- data[append(var, 'Name')]

temp <- temp[complete.cases(temp), ]


for (i in 1:length(var)){
  temp[var[i]] <- normalize(temp[var[i]])
}


data2 <- temp%>%
  filter(Name%in%names)

rownames(data2) <- data2$Name 
data2 <- data2 %>%
  select(-Name)
data2 <- rbind(rep(1, length(var)), rep(0,length(var)), data2)

scale_colours=c(rainbow(length(names)))
radarchart(data2, pcol=scale_colours, plwd=5, vlcex=2)
legend(x=1.7, 
       y=1, 
       legend = rownames(data2[-c(1,2),]), 
       bty = "n", pch=20 , col = scale_colours, cex = 2)
}

best_players <- function(data, position, var, num){
temp <- data%>%
        filter(Position==position)%>%
        top_n(num, (!!as.symbol(var)))

ggplot(temp)+
  geom_col(aes(reorder(Name, (!!as.symbol(var))), (!!as.symbol(var))), fill=viridis(10)[5])+
  theme_minimal()+
  labs(x='Zawodnik', y='Statystyka', title='Najlepsi zawodnicy na danej pozycji według danej statystyki')+
  theme(axis.text.x = element_text(hjust=1, angle=45), axis.line.x = element_blank())
         
}

y_x <- function(data, position, var1, var2, var3){
temp <- data%>%
        filter(Position==position)

ggplot(temp, aes((!!as.symbol(var2)), (!!as.symbol(var1))))+
  geom_point(aes(colour=(!!as.symbol(var3))), size=8) +
  geom_smooth(aes((!!as.symbol(var2)), (!!as.symbol(var1))),method = "lm", se = FALSE, colour=viridis(10)[2])  +
  theme_bw()+
  scale_color_gradientn(colours=c(viridis(10)[10], viridis(10)[1]))+
  theme(legend.position = 'bottom')
         
}

players_name <- function(data, position, var1, var2, var3, num){

temp <- data%>%
        filter(Position==position)%>%
        top_n(num, (!!as.symbol(var1)))



ggplot(temp)+
  geom_text(aes((!!as.symbol(var2)), (!!as.symbol(var1)), label=Name, colour=(!!as.symbol(var3))), size=4.5) +
  theme_bw()  +
  scale_color_viridis(begin=0.8, end=0.3)+
  theme(legend.position = 'bottom')+
  xlim(min(temp[var2])*0.85 , max(temp[var2])*1.15)
}

```
Podsumowanie
===================================== 

Inputs {.sidebar}
-------------------------------------

Wybierz zmienne do wyświetlenia

```{r}

selectInput("position",
                   label = "Wybierz pozycję",
                   choices = unique(data$Position),
                    selected = 'Napastnik')
selectInput("y",
               label = "Wybierz zmienną objaśnianą",
               choices = names(data), selected = 'Goals')
selectInput("x",
               label = "Wybierz zmienną objaśniającą",
               choices = names(data), selected = 'Passes')
selectInput("fill",
               label = "Wybierz zmienną do wypełnienia",
               choices = names(data), selected = 'Assists')
sliderInput("number_of_players",
                label= "Wybierz liczbę piłkarzy do wyświetlenia",
                min = 3, max = 30, value = 10)

```

Column {.tabset}
-------------------------------------

### Najlepsi zawodnicy według statystyki y

```{r}
suppressWarnings(renderPlotly({
     best_players(data, input$position, input$y, input$number_of_players)
   }))
```

### Najlepsi zawodnicy według statystyki x

```{r}
suppressWarnings(renderPlotly({
     best_players(data, input$position, input$x, input$number_of_players)
   }))
```

Column {.tabset}
-------------------------------------

### Zależność statystyki y od x

```{r}
suppressWarnings(renderPlotly({
     y_x(data, input$position, input$y, input$x, input$fill)
   }))
```

### Zależność statystyki y od x wśród najlepszych

```{r}
suppressWarnings(renderPlotly({
     players_name(data, input$position, input$y, input$x, input$fill, input$number_of_players)
   }))
```

Wykresy radarowe
===================================== 

Inputs {.sidebar}
-------------------------------------

Wybierz zmienne do wyświetlenia

```{r}

selectInput("names",
                   label = "Wybierz piłkarzy",
                   choices = unique(data$Name),
                   multiple = TRUE, selected = c('Jamie Vardy', 'Mohamed Salah'))
selectInput("var",
               label = "Wybierz statystyki",
               choices = names(data),
               multiple = TRUE, selected = c('Shots', 'Goals', 'Assists', 'Passes'))

```

Column 
-------------------------------------

```{r}
suppressWarnings(renderPlot({
     radar(data, input$var, input$names)
   }, height = 1000))
```

<!-- ### Top 30 surveys -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_survey(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->

<!-- ``` -->

<!-- ### YoY -->


<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_yoy(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->

<!-- Column {data-width=300} -->
<!-- ------------------------------------- -->

<!-- ### Monthly -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_month(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->


<!-- ### Processing -->
<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_tasks(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->

<!-- Surveys - tables -->
<!-- ===================================== -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Hours by Survey -->

<!-- ```{r} -->
<!-- renderTable(table_quest(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Hours by Month -->

<!-- ```{r} -->
<!-- renderTable(table_month(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->

<!-- ### Hours by Task -->

<!-- ```{r} -->
<!-- renderTable(table_task(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->


<!-- Shared Work - Teams -->
<!-- ===================================== -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Shared Work Team -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_team(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->

<!-- ### Shared Work Energy/SIRS/Healthcare -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_energy(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->

<!-- Column -->
<!-- ------------------------------------- -->

<!-- ### Shared Work General Industry -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_gi(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->


<!-- ### Shared Work Professionals -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_prof(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->


<!-- Shared Work - Full -->
<!-- ===================================== -->


<!-- ```{r} -->
<!-- suppressWarnings(renderPlot({ -->
<!--      plot_sharedwork_full(input$survey, input$team, input$wfm, input$month, input$tasks, input$level) -->
<!--    })) -->
<!-- ``` -->

<!-- Stats per Team {data-orientation=rows} -->
<!-- ===================================== -->

<!-- Row {data-height=350} -->
<!-- ------------------------------------- -->

<!-- ### Table stats per Team -->

<!-- ```{r} -->
<!-- renderTable(table_stats(input$survey, input$team, input$wfm, input$month, input$tasks)) -->
<!-- ``` -->

<!-- Row {data-height=650} -->
<!-- ------------------------------------- -->

<!-- ### Plot stats overall -->

<!-- ```{r} -->
<!-- suppressWarnings(renderPlotly({ -->
<!--      plot_team_stats(input$survey, input$team, input$wfm, input$month, input$tasks) -->
<!--    })) -->
<!-- ``` -->
